workflows:
  ios-release:
    name: Build iOS IPA (iPhone)
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Package to IPA
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r bago_admin.ipa Payload
    artifacts:
      - build/ios/ipa/bago_admin.ipa
      - build/ios/iphoneos/Runner.app
